### ISSUE TITLE
Change to github templates?

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/package-template#7]
I was just wondering if we maybe want to change this to github templates?

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

It would remove the dependency on cookiecutter.
Thoughts?

**Comment by rbeyer** [comment]
As long as they are feature-equivalent, its a toss-up, I suppose.  The advantage of forking from cookie-cutter is that theoretically people that might know more about Python repos might discover or add something exciting at that level that we could then incorporate.

I'm not actually seeing a lot of documentation about "GitHub templates" but maybe I'm just looking in the wrong place?

**Comment by michaelaye** [comment]
the above link doesn't help? I agree that cookiecutter could be and/or stay more Python focused...

**Comment by rbeyer** [comment]
No, it doesn't.  There are instructions for creating a repo from a template, but I don't see anything about how to *create* a template repo, but I may well be missing something, I didn't spend a lot of time.

**Comment by michaelaye** [comment]
The link was right there ;)
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by michaelaye** [comment]
it seems amazingly simple, i like that part. Just put stuff in and put the hook that it is a template repo. Much more straightforward. However, no name/form substitutions apparently, as they are possible in the cookiecutter which are real text templates.

**Comment by rbeyer** [comment]
Hm, I wouldn't call that a "template" so much as "you can copy this repo instead of forking it" which seems to have less features than the the cookie-cutter mechanism that has string templating and provides some options during creation.  However, I don't mean to be argumentative, especially as I'm not as informed, and if you think GitHub templates would be better, then go for it.

**Comment by michaelaye** [comment]
No, this was an honest question on opinions about it because I found out about them by chance. I agree that that the cookiecutter is much more powerful.

--
Michael Aye
LASP / CU Boulder
